### PR TITLE
Fixes, CI/CD for automatic pr and master deployment

### PR DESCRIPTION
**Pull request by shal**

### CODE REVIEW

**Comment by ashanaakh** [comment]
@mod We should `make ci` after merged.

**Comment by ashanaakh** [comment]
PR deployment and master deployment using kite-concourse-resourse

__Examples:__
https://pr1.peatio.tech
https://www.pr1.peatio.tech

https://www.peatio.tech
https://peatio.tech

**Comment by naamaesa** [comment]
Why is this still here since December 2017? :)

**Comment by shal** [comment]
@naamaesa nice question 😄

**Pull request closed without merging**
